# Generated by Django 4.0.4 on 2022-05-22 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_budi_catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 21, 43, 10, 661286)),
        ),
    ]
