# Generated by Django 4.0.4 on 2022-05-22 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_budi_catalogue', '0002_alter_journal_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ownership_stat',
        ),
        migrations.RemoveField(
            model_name='comicbook',
            name='ownership_stat',
        ),
        migrations.AddField(
            model_name='book',
            name='ownership_status',
            field=models.CharField(choices=[('00', "Don't Own, Don't Want"), ('01', "Don't Own, Want"), ('10', "Own, Don't Want"), ('11', 'Own, Want')], default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='comicbook',
            name='ownership_status',
            field=models.CharField(choices=[('00', "Don't Own, Don't Want"), ('01', "Don't Own, Want"), ('10', "Own, Don't Want"), ('11', 'Own, Want')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 21, 53, 42, 979514)),
        ),
        migrations.DeleteModel(
            name='OwnershipStatus',
        ),
    ]
