# Generated by Django 4.0.4 on 2022-05-22 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_budi_catalogue', '0003_remove_book_ownership_stat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='genre_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='illustrator',
            old_name='illustrator_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mediumtype',
            old_name='genre_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='journal',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 22, 25, 44, 223745)),
        ),
    ]
