# Generated by Django 4.0.4 on 2022-05-22 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_budi_catalogue', '0004_rename_author_name_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comicbook',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comicbook',
            name='rental_status',
            field=models.BooleanField(blank=True, verbose_name='For Rent?'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 22, 31, 8, 566417)),
        ),
    ]
