# Generated by Django 4.0.4 on 2022-05-22 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_budi_catalogue', '0005_alter_book_rating_alter_comicbook_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='book_authors', to='book_budi_catalogue.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='book_genres', to='book_budi_catalogue.genre'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 22, 35, 9, 289511)),
        ),
    ]
