# Generated by Django 4.0.4 on 2022-05-22 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_budi_catalogue', '0006_alter_book_authors_alter_book_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicbook',
            name='authors',
            field=models.ManyToManyField(related_name='comic_authors', to='book_budi_catalogue.author'),
        ),
        migrations.AlterField(
            model_name='comicbook',
            name='genres',
            field=models.ManyToManyField(related_name='comic_genres', to='book_budi_catalogue.genre'),
        ),
        migrations.AlterField(
            model_name='comicbook',
            name='illustrators',
            field=models.ManyToManyField(related_name='comic_illustrators', to='book_budi_catalogue.illustrator'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 7, 58, 47, 905986)),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='books',
            field=models.ManyToManyField(related_name='shelf_books', to='book_budi_catalogue.book'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='comics',
            field=models.ManyToManyField(related_name='shelf_comics', to='book_budi_catalogue.comicbook'),
        ),
    ]
