# Generated by Django 4.0.4 on 2022-05-22 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_budi_catalogue', '0007_alter_comicbook_authors_alter_comicbook_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookbygenre',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookbygenre',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='bookbyshelf',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookbyshelf',
            name='shelf',
        ),
        migrations.RemoveField(
            model_name='comicbyauthor',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comicbyauthor',
            name='comic',
        ),
        migrations.RemoveField(
            model_name='comicbygenre',
            name='comic',
        ),
        migrations.RemoveField(
            model_name='comicbygenre',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='comicbyillustrator',
            name='comic',
        ),
        migrations.RemoveField(
            model_name='comicbyillustrator',
            name='illustrator',
        ),
        migrations.RemoveField(
            model_name='comicbyshelf',
            name='comic',
        ),
        migrations.RemoveField(
            model_name='comicbyshelf',
            name='shelf',
        ),
        migrations.AlterField(
            model_name='journal',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 8, 3, 4, 26278)),
        ),
        migrations.DeleteModel(
            name='BookByAuthor',
        ),
        migrations.DeleteModel(
            name='BookByGenre',
        ),
        migrations.DeleteModel(
            name='BookByShelf',
        ),
        migrations.DeleteModel(
            name='ComicByAuthor',
        ),
        migrations.DeleteModel(
            name='ComicByGenre',
        ),
        migrations.DeleteModel(
            name='ComicByIllustrator',
        ),
        migrations.DeleteModel(
            name='ComicByShelf',
        ),
    ]
