# Generated by Django 4.0.4 on 2022-05-22 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_budi_catalogue', '0008_remove_bookbygenre_book_remove_bookbygenre_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='book_budi_catalogue.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, to='book_budi_catalogue.genre'),
        ),
        migrations.AlterField(
            model_name='comicbook',
            name='authors',
            field=models.ManyToManyField(to='book_budi_catalogue.author'),
        ),
        migrations.AlterField(
            model_name='comicbook',
            name='genres',
            field=models.ManyToManyField(blank=True, to='book_budi_catalogue.genre'),
        ),
        migrations.AlterField(
            model_name='comicbook',
            name='illustrators',
            field=models.ManyToManyField(blank=True, to='book_budi_catalogue.illustrator'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 8, 7, 45, 110193)),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='books',
            field=models.ManyToManyField(to='book_budi_catalogue.book'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='comics',
            field=models.ManyToManyField(to='book_budi_catalogue.comicbook'),
        ),
    ]
